/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.iflytek.spider.schema;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(1)
public class BYTE extends org.apache.avro.specific.SpecificFixed {}
