/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.iflytek.spider.schema;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
public class MD5 extends org.apache.avro.specific.SpecificFixed {}
